on: [ push, pull_request ]
name: Continuous Integration

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Lua 5.4
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.4"

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

      # utfTerminal is temp
      - name: Test
        run: |
          busted -p .spec -o utfTerminal

